version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:\Users\jonghyun\Desktop\posomo\saltit-server-for-cicd\operationfile\default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: backend-nginx
  web1 :
    image: jonghyunbaik/saltit:latest
    ports:
      - "8080:8080"
    container_name: api-server1
  web2 :
    image: jonghyunbaik/saltit:latest
    ports:
      - "8081:8080"
    container_name: api-server2
    